apiVersion: v1
kind: ConfigMap
metadata:
  name: students-service
data:
  db_name: students_db
  db_host: jdbc:postgresql://postgres16:5432/students_db
  courses_url: http://courses-service:8081


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: courses-service
data:
  db_name: courses_db
  db_host: jdbc:mysql://mysql8:3306/courses_db
  students_url: http://students-service:8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-server
data:
  client_url: http://gateway-server:8090

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-server
data:
  students_url: http://students-service:8080/students
  courses_url: http://courses-service:8081/courses
  auth_server: http://authorization-server:9000
  redirect_url: http://gateway-server:8090/authorized


