apiVersion: v1
kind: Service
metadata:
  name: mysql8
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql8
  type: ClusterIP
  # ClusterIP => PARA COMUNICACION DENTROD DEL CLUSTER
  # NODEPORT => PARA EXPONER UN SERVICIO MEDIANTE UN PUERTO DEL CLUSTER
  # LOADBALANCER => EXPONE O TE ORTORGA UNA IP EXTERNA MEDIANTE LA CUAL TE PUEDAS COMUNICAR
