apiVersion: v1
kind: Secret
metadata:
  name: students-service
type: Opaque #Para que se encripten los valores en base64
  #stringData >Para ver los en texto plano
data:
  db_username: cG9zdGdyZXM=
  db_password: YWRtaW4=
---

apiVersion: v1
kind: Secret
metadata:
  name: courses-service
type: Opaque #Para que se encripten los valores en base64
#stringData >Para poder ingresar valores en texto plano
data: #data, es para poder ingresar datos encriptados
  db_username: cm9vdA==
  db_password: cm9vdA==





